import type { Metadata } from "next";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Blog app",
  description: "Generated by create next app",
};

type Props = Readonly<React.PropsWithChildren>;

export default function Layout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <div className="relative min-h-svh w-full bg-white text-neutral-800">
          {children}
        </div>
      </body>
    </html>
  );
}
