import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/app/globals.css";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog app",
  description: "Generated by create next app",
};

type Props = Readonly<React.PropsWithChildren>;

export default function Layout({ children }: Props) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
